# Generated by Django 2.2.8 on 2020-10-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
        ),
    ]
