# Generated by Django 2.2.8 on 2020-11-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201115_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
        ),
    ]
