# Generated by Django 2.2.8 on 2021-01-11 03:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
