# Generated by Django 2.2.8 on 2020-11-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201115_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='username',
        ),
    ]
