# Generated by Django 2.2.8 on 2020-10-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artist_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='slug',
            new_name='tag',
        ),
    ]
