# Generated by Django 2.2.8 on 2020-11-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201115_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
    ]
