# Generated by Django 2.2.8 on 2021-01-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210111_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='CITY',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
