# Generated by Django 2.2.8 on 2020-11-23 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201116_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
