# Generated by Django 2.2.8 on 2020-11-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tweeter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
