# Generated by Django 2.2.8 on 2021-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210111_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
