# Generated by Django 2.2.8 on 2021-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210111_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
