# Generated by Django 2.2.8 on 2020-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201130_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='tweeter',
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
