# Generated by Django 2.2.8 on 2020-10-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201026_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.SlugField(default='please enter a tag...'),
        ),
    ]
