# Generated by Django 2.2.8 on 2020-11-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201130_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='billing_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAdress'),
        ),
    ]
