# Generated by Django 2.2.8 on 2021-01-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210111_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='time_stamp',
        ),
    ]
