# Generated by Django 2.2.8 on 2020-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_artist_billing_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='billing_adress',
        ),
    ]
