# Generated by Django 2.2.8 on 2020-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201028_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='slug',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
