# Generated by Django 2.2.8 on 2020-11-06 20:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201105_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_artist',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
