# Generated by Django 2.2.8 on 2021-01-17 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Attach Image'),
        ),
    ]
