# Generated by Django 2.2.8 on 2020-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201206_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='cardno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
