# Generated by Django 2.2.8 on 2020-12-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201206_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='MMYY',
            field=models.DateTimeField(blank=True),
        ),
    ]
