# Generated by Django 2.2.8 on 2021-01-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210120_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='mailing_address',
        ),
    ]
