# Generated by Django 2.2.8 on 2020-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201206_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='MMYY',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
