# Generated by Django 2.2.8 on 2020-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201206_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='MMYY',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
