# Generated by Django 2.2.8 on 2020-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
