# Generated by Django 2.2.8 on 2020-12-10 19:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_artist',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqj36cjxw/image/upload/v1607600679/Rectangle_52_jiszkm.png', max_length=255, verbose_name='image'),
        ),
    ]
