# Generated by Django 2.2.8 on 2020-12-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dialog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
