# Generated by Django 2.2.8 on 2021-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210101_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Tag'),
        ),
    ]
