# Generated by Django 2.2.8 on 2021-01-05 21:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210105_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqj36cjxw/image/upload/v1609854605/uis0nvmmwdkfkhydtenu.jpg', max_length=255, verbose_name='image'),
        ),
    ]
