# Generated by Django 2.2.8 on 2021-01-05 21:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_show_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_artist',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqj36cjxw/image/upload/v1607600679/Rectangle_52_jiszkm.png', max_length=255, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqj36cjxw/image/upload/v1609854605/uis0nvmmwdkfkhydtenu.jpg', max_length=255, verbose_name='Poster'),
        ),
    ]
